### ISSUE TITLE
how to check the rotation in figures?

### ISSUE THREAD

**Issue by yinkaiming1987** [stanfill/rotationsC#2]
Dear Bryan,

Could I ask how to check the rotations in figures? As I want to rotate around the x-axis for 45 degree, then around y-axis for 60 degree. I use the codes below, and want to check the process step by step in plots, but it seems the plotting doesn't show any rotations, should I use other functions?
# Code:

library('rotations')

x <- c(1,0,0)
y <- c(0,1,0)

r1 <- as.SO3(x, pi/4)
r2 <- as.SO3(y, pi/3)
r3 <- r1 + r2

plot(r3, interactive = TRUE)
# done

Thanks,
Kaiming

**Comment by stanfill** [comment]
Hi Kaiming,
It is difficult to see the step-by-step process using the `interactive=TRUE` option because the coordinate axis is so pliable.  Also, for better or for worse, the default center for `plot.SO3` is the mean of the data provided.  In this case, the only data provided is `r3` so the mean is `r3` and the plot will center around that.  Meaning, it will appear like there hasn't been any rotation whatsoever.  To fix that, try setting the center option to the identity rotation by setting `center=id.SO3`.  I would also add `r1` and `r2` to the plot to see the whole process.  Try the following:

```
library(rotations)
x <- c(1,0,0)
y <- c(0,1,0)
r1 <- as.SO3(x,pi/4)
r2 <- as.SO3(y,pi/3)
r3 <- r1+r2
all_rs <- as.SO3(rbind(r1,r2,r3))
plot(all_rs,center=id.SO3, col=c(1,2,3),label_points=c("r1","r2","r3"))
```

You can also look at one axis at a time by changing the `col` option to `col=1` for the x-axis and similarly for the the other two axes.

For your example in particular, it would be nice if you could connect the points to track the movement more easily.  That is possible, but not for the faint of heart.  I will try to make that available in future releases.
Thanks,
Bryan

**Comment by yinkaiming1987** [comment]
Thanks Bryan,

That looks great! It seems like a right-hand coordinate system?

Cheers,
Kaiming

**Comment by stanfill** [comment]
That's correct.
-Bryan
